compile error with musl libc
```
In file included from /usr/include/linux/wireless.h:74:0,
                 from hcxdumptool.c:25:
/usr/include/linux/if.h:142:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^~~~~
```


since you disabled issue tracker for this repo, i needed to create a fake PR.